---
kind: pipeline
name: commitlint
steps:
  - name: npm install
    image: &node_image node:10.16.0-alpine
    commands:
      - npm i
  - name: tag/commitlint
    image: *node_image
    commands:
      - npx commitlint --from HEAD~1 --to HEAD
    when:
      event:
        - tag
        - push
  - name: pr/commitlint
    image: *node_image
    commands:
      - npx commitlint --from master --to HEAD || exit 1
    when:
      event:
        - pull_request
---
kind: pipeline
name: build
workspace:
  base: /go
  path: src/github.com/suzuki-shunsuke/durl
steps:
  - name: durl
    image: &image_go golang:1.12.6
    commands:
      - bash scripts/durl.sh
    environment:
      GO111MODULE: on
  - name: go vet
    image: *image_go
    commands:
      - go vet ./...
    environment:
      GO111MODULE: on
  - name: golangci-lint
    image: golangci/golangci-lint:v1.17.1
    commands:
      - golangci-lint run
    environment:
      GO111MODULE: on
  - name: go test
    image: *image_go
    commands:
      - go test -race -covermode=atomic ./...
    environment:
      GO111MODULE: on
    when:
      event:
        - pull_request
  - name: codecov
    image: *image_go
    commands:
      - bash scripts/codecov-test.sh
    environment:
      GO111MODULE: on
      CODECOV_TOKEN:
        from_secret: codecov_token
    when:
      event:
        - push
        - tag
  - name: fetch tags
    image: plugins/git
    commands:
      - git fetch --tags
  - name: tag dummy
    image: plugins/git
    commands:
      # bash not found
      - sh scripts/tag-dummy.sh
    when:
      event:
        - pull_request
        - push
  - name: build with goreleaser (not release)
    image: &docker_goreleaser goreleaser/goreleaser:v0.110.0
    commands:
      - goreleaser release --skip-publish
    environment:
      GO111MODULE: on
    when:
      event:
        - push
        - pull_request
  - name: build and release with goreleaser
    image: *docker_goreleaser
    commands:
      - goreleaser release
    environment:
      GO111MODULE: on
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        - tag
  - name: build and push docker
    image: &docker_plugin plugins/docker:18.09.0
    settings:
      tags:
        - latest
        - "${DRONE_TAG##v}"
      repo: quay.io/suzuki_shunsuke/durl
      registry: quay.io
      username:
        from_secret: quayio_username
      password:
        from_secret: quayio_password
    when:
      event:
        - tag
  - name: build docker (not push)
    image: *docker_plugin
    settings:
      repo: quay.io/suzuki_shunsuke/durl
      registry: quay.io
      dry_run: true
    when:
      event:
        - pull_request
        - push
