---
# configuration file of durl, which is a CLI tool to check whether broken urls are included in files.
# https://github.com/suzuki-shunsuke/durl
ignore_urls:
  - https://github.com/suzuki-shunsuke/durl
  - https://github.com/suzuki-shunsuke/durl/blob/master/.circleci/config.yml
  - https://github.com/suzuki-shunsuke/durl/blob/master/package.json
  - https://github.com/suzuki-shunsuke/durl/blob/master/internal/domain/version.go
  - https://github.com/suzuki-shunsuke/durl/releases
  - https://circleci.com/gh/suzuki-shunsuke/durl
  - http://example.com/foo
  - http://example.com/bar
