---
# configuration file of durl, which is a CLI tool to check whether broken urls are included in files.
# https://github.com/suzuki-shunsuke/durl
ignore_urls:
  - http://example.com/foo
  - http://example.com/bar
