---
# configuration file of durl, which is a CLI tool to check whether broken urls are included in files.
# https://github.com/suzuki-shunsuke/durl
ignore_urls:
- https://github.com/suzuki-shunsuke/durl
- http://example.com/bar
