---
default:
items:
- src:
    file: internal/domain/interface.go
    interface: Fsys
  dest:
    package: test
    file: internal/test/fsys_mock.go
- src:
    file: internal/domain/interface.go
    interface: Logic
  dest:
    package: test
    file: internal/test/logic.go
- src:
    file: internal/domain/interface.go
    interface: HTTPClient
  dest:
    package: test
    file: internal/test/http_client.go
